:sparkles: Finished first pass of dyetide!

diff --git a/dyetide b/dyetide
--- a/dyetide
+++ b/dyetide
@@ -11,17 +11,18 @@ examples:
  dyetide -x file
  dyetide -r file
 EOM
-    exit 1
+    exit 0
 }
 
 error() {
     printf "error: %s\n" "$1" 1>&2
-    ${2:+exit $2}
+    exit 1
 }
 
+
 success() {
-    printf "success: %s\n" "$1"
-    ${2:+exit 0}
+    printf "success: %s\n" "$1" 2>&1
+    exit 0
 }
 
 # to be placed in install script
@@ -48,7 +49,7 @@ replace_all_hex() {
         mapfile -t allhexvalues < <(grep -P -o "${regex}" "${filename}")
 
         if [[ ${#allhexvalues[@]} -eq 0 ]]; then
-            error "no hex values found in $filename" 2
+            error "no hex values found in $filename"
         fi
 
         # $hexvalues contains only unique hex values from $allhexvalues
@@ -57,14 +58,10 @@ replace_all_hex() {
         done < <(printf "%s\0" "${allhexvalues[@]}" | sort -uz)
 
         for hex in "${hexvalues[@]}"; do
-            # replace with repaint after installation script is done
             rgb=$(./dependencies/repaint -x "$hex")
-            # sed looks for hex codes with one trailing space...
-            sed -i "s/\s${hex}\s/ ${rgb} /g" "$filename"
-            # or a preceding space and a trailing space...
-            sed -i "s/${hex}\s/${rgb} /g" "$filename"
-            # or a preceding space and a trailing semicolon (css files)
-            sed -i "s/\s${hex};\s/ ${rgb};/g" "$filename"
+            sed -i "s/ ${hex} / ${rgb} /g" "$filename"
+            sed -i "s/${hex} /${rgb} /g" "$filename"
+            sed -i "s/ ${hex};/ ${rgb};/g" "$filename"
         done
 
         success "${filename}'s hex codes converted to rgba" 0
@@ -77,27 +74,32 @@ replace_all_rgb() {
     local filename
     filename="${2}"
     if [[ -f "$filename" ]]; then
-        local allrgbvalues rgbvalues rgb
+        local allrgbvalues rgbvalues rgbarr
         IFS=$'\n'
-        regex='rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}[)]|rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}, [0-1].[0-9][)]'
-        allrgbvalues=$(grep -Po "${regex}" "${filename}" | sed 's/^/\"/g' | sed 's/$/\"/g')
+        regex='\s?rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}[)]|rgb[a]?[(][0-9]{1,3}, [0-9]{1,3}, [0-9]{1,3}, [0-1]?.[0-9][0-9]?[)]\s?'
+        allrgbvalues=$(grep -Po "${regex}" "${filename}")
 
-        read -d '' -r -a rgbvalues <<< "${allrgbvalues}"
+        read -d '' -r -a rgbarr <<< "${allrgbvalues}"
+
+        if [[ ${#rgbarr[@]} -eq 0 ]]; then
+            error "no rgb values found in $filename"
+        fi
 
         while IFS= read -r -d '' x; do
-            rgb+=("$x")
-        done < <(printf "%s\0" "${rgbvalues[@]}" | sort -uz)
+            rgbvalues+=("$x")
+        done < <(printf "%s\0" "${rgbarr[@]}" | sort -uz)
 
-        # for hex in "${hexvalues[@]}"; do
-            # rgb=$(./dependencies/repaint -x "$hex")
-            # sed -i "s/\s${hex}\s/ ${rgb} /g" "$filename"
-            # sed -i "s/${hex}\s/${rgb} /g" "$filename"
-            # sed -i "s/\s${hex};\s/ ${rgb};/g" "$filename"
-        # done
+        for rgb in "${rgbvalues[@]}"; do
+            hex=$(./dependencies/repaint -r "$rgb")
+            sed -i "s/ ${rgb} / ${hex} /g" "$filename"
+            sed -i "s/${rgb} /${hex} /g" "$filename"
+            sed -i "s/ ${rgb};/ ${hex};/g" "$filename"
+            sed -i "s/${rgb}/${hex} /g" "$filename"
+        done
 
-        printf '%s\n' "${rgb[@]}"
+        success "${filename}'s rgba codes converted to hex"
     else
-        error "$filename not found" 2
+        error "$filename not found"
     fi
 }
 
